## Book
1. Hikosaka K., Sasaki T., Kamiyama C., **Katabuchi M.**, Oikawa S., Shimazaki M., Kimura H. and Nakashizuka T. (2016), Trait-Based Approaches for Understanding Species Niche, Coexistence, and Functional Diversity in Subalpine Moorlands.  Structure and Function of Mountain Ecosystems in Japan.

## Software
2020
: **ztpln**: Zero-Truncated Poisson Lognormal Distribution, [R CRAN package](https://cran.r-project.org/web/packages/ztpln/index.html)

2015
: **LeafArea**: Rapid Digital Image Analysis of Leaf Area,  [R CRAN package](https://cran.r-project.org/web/packages/LeafArea/index.html)

2015
: **mglmn**: Model Averaging fro Multivariate GLM with Null Models, R CRAN package  [R CRAN package](https://cran.r-project.org/web/packages/mglmn/index.html)

## Teaching Experience
2019-
: How do we measure and study biological diversity?, Advanced Field course in Ecology and Conservation, Xishuangbanna Tropical Botanical Garden, Chinese Academy of Sciences, China

2013
: Experimental Design and Data Analysis, ATBC Asia-Pacific chapter, Banda Aceh, Indonesia

2013
: R and generalized linear models, Xishuangbanna Tropical Botanical Garden, Chinese Academy of Sciences, China

## Service
2015-2017
: []()
: Working Group Member of INNGE, International Network of Next-Generation Ecologists

2015-2017
: []()
: INNGE manager, The Japan Society of Tropical Ecology

2013-
: []()
: Statistical editor for Lepcey, The Journal of Tropical Asian Entomology

Reviewer for journals (~ 12 per year):
\begin{multicols}{2}
- AoB Plants

- Biotropica

- BMC Evolutionary Biology

- Ecological Research

- Ecology Letters

- Ecosphere

- Forest Ecology and Management

- Frontiers in Plant Science

- Functional Ecology

- Journal of Applied Ecology

- Journal of Ecology

- Journal of Plant Research

- Journal of Sustainable Forestry

- Journal of Vegetation Science

- Nature Communications

- Oecologia

- Oikos

- Plant Ecology

- PLOS ONE

- Scientific Reports
\end{multicols}


## Awards and Prizes
2012
: Dean’s award for excellence, Graduate School of Life Sciences (Doctoral Program), Tohoku University

2009
: Dean’s award for excellence, Graduate School of Life Sciences (Master’s Program), Tohoku University

## Invited Seminars

2021
: Introduction to visualization using ggplot2, International Institute of Tropical Agriculture, Kenya

2018
: A quantitative model for divergent drivers of leaf trait variation within and among plant species, Xishuangbanna Tropical Botanical Garden, China

2018
: Species coexistence and functional traits. Graduate School of Life Sciences, Tohoku University, Japan

2018
: Species coexistence and functional traits. Graduate School of Environment and Information Sciences, Yokoyama National University, Japan

2016
: Decomposing leaf mass into photosynthetic and structural components explains divergent patterns of trait variation within and among plant species. Department of Ecology and Evolutionary Biology, Princeton University, NJ

2013
: Additive partitioning of functional diversity in plant communities, Xishuangbanna Tropical Botanical Garden, China


## International Meetings
**Invited**

2015
: **Masatoshi Katabuchi**, "Future perspective for functional trait research", Organized session on "Achievements and outstanding questions for trait-based forest ecology", 62nd ESJ Annual meeting, Kagoshima, Japan

2014
: **Masatoshi Katabuchi (Organizer)**, “Seedling dynamics and its consequence to community assembly processes in a tropical forest”, Symposium on "Integrating the structure and dynamics of tree communities to uncover the mechanisms underlying species coexistence", 61st ESJ Annual meeting, Hiroshima, Japan

2011
: **Masatoshi Katabuchi** and Hiroko Kurokawa "Community assembly and demography of tropical tree species", Workshop on "Life history regulation of forest trees: towards cross-biome analysis", Sapporo, Japan

**Submitted**

2019
: **Masatoshi Katabuchi**, Kaito Umemura, Thomas Koffel, Litchman Elena, Klausmeier A Christopher, "Combining metacommunity and trait-based approaches predicts species abundances distributions in biological communities", 66th ESJ Annual meeting, Kobe, Japan

2015
: **Masatoshi Katabuchi**, Kaoru Kitajima, Joesph Wright, Jeanne Osnas and Jeremy Lichstein "Decomposing leaf mass into photosynthetic and structural components explains diverge patterns of trait variation within vs. among plant communities", 100th ESA Annual meeting, Baltimore, USA

2014
: **Masatoshi Katabuchi**, Takehiro Sasaki, Chiho Kamiyama, Masaya Shimazaki, Tohru Nakashizuka and Kouki Hikosaka “Intraspecific trait variations affect spatial patterns of functional diversity among moorland plant communities”, 99th ESA Annual meeting, Sacramento, USA.

2013
: **Masatoshi Katabuchi**, Sylvester Tan and Tohru Nakashizuka “Negative density dependence reduces survival rates of common tree species in a species-rich tropical rain forest", ATBC, San Jose, Costa Rica

2012
: **Masatoshi Katabuchi**, Hiroko Kurokawa, Stuart Davies, Sylvester Tan and Tohru Nakashizuka "Soil resource availability shapes community trait structure in a species-rich dipterocarp forest", ATBC Asia-Pacific chapter, XTBG, China

2011
: **Masatoshi Katabuchi**, Hiroko Kurokawa, Sylvester Tan, Stuart J. Davies, and Tohru Nakashizuka, “Nonrandom abundance distributions of a tropical tree community: evidence from traits correlation at a local scale”. ATBC, Arusha, Tanzania

2010
: **Masatoshi Katabuchi**, Hiroko Kurokawa, Sylvester Tan, and Tohru Nakashizuka, “Soil variation and functional trait assembly in a diverse dipterocarp forest”. 95th ESA Annual meeting, Pittsburgh, USA

2009
: **Masatoshi Katabuchi**, Jun Yokoyama, and Tohru Nakashizuka, “Inbreeding and mating structure in a dioecious-fig pollinating wasp”. ATBC, Marburg, Germany

## Outreach
2015
: Masatoshi Katabuchi “Leaves and tropical rainforests”. Invited by the Japanese Association of Interdisciplinary Study Group in University Florida

## Languages
Japanese (native), English (fluent), Malay (basic), Chinese-Mandarin (basic)

## Graduate Students

Zhou Cong, 2021 - Present, M.Sc. Student, Recipient of UCAS Scholarship.
